package:
  name: quirkyshopping
  version: 1.0

source:
  git_rev: 1.0
  git_url: https://github.com/LoesjeNL/quirkyshopping.git

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python
    - numpy
    - wxpython

    
test:
  imports:
    - quirkyshopping

about:
  home: https://github.com/LoesjeNL/quirkyshopping
  license: GPL3
  license_file: LICENSE
  description: 'The package allows you to design your own T-shirt'
